### ISSUE TITLE
已经提供accesstoken了，test.py中没看到share token设置

### ISSUE THREAD

**Issue by RootSir** [KunBuFZ/Pandora-Token-Get-and-Use#1]
python3 test.py 
Error: 401 {"error":{"message":"you didn't provide a share token","type":"invalid_request_error","param":null,"code":null}}

**Comment by KunBuFZ** [comment]
需要先在share.py获取fk(即share token),再在test.py中输入fk 而不是access token

**Comment by KunBuFZ** [comment]
![image](https://github.com/KunBuFZ/Pandora-Token-Get-and-Use/assets/152124473/0282ceae-1aeb-4140-b95d-1f49b9c553e8)
此处填fk 即可

**Comment by KunBuFZ** [comment]
已经将变量修改为正确的名称
